#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Run checkstyle before commit.
SCRIPT_DIR=$(dirname "$0")
SCRIPT_ABS_PATH=`cd "$SCRIPT_DIR"; pwd`
$SCRIPT_ABS_PATH/../../gradlew  -PcheckCommit="true" checkstyleLocal
if [ $? -eq 0   ]; then
    echo "checkstyle OK"
else
    exit [[ $ERROR_INFO =~ "checkstyle" ]] && exit 1
fi

# Run ktlint before commit.
$SCRIPT_ABS_PATH/../../gradlew  -PcheckCommit="true" ktlintLocal
if [ $? -eq 0   ]; then
    echo "ktlint OK"
else
    exit [[ $ERROR_INFO =~ "ktlint" ]] && exit 1
fi
